# Generated by Django 3.2.6 on 2021-08-12 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.TextField(blank=True, max_length=12)),
                ('acc', models.IntegerField(blank=True)),
                ('ifsc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromt', models.TimeField(blank=True)),
                ('to', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.TextField()),
                ('gender', models.TextField()),
                ('dob', models.DateField()),
                ('type', models.BooleanField(default=False)),
                ('expectedOTP', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('creds', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.ImageField(blank=True, upload_to='media')),
                ('phone', models.IntegerField(blank=True)),
                ('duration_in_mins', models.IntegerField()),
                ('price', models.IntegerField(default=500)),
                ('available', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.slot')),
                ('bank', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.bankaccount')),
                ('creds', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr1', models.TextField(blank=True)),
                ('addr2', models.TextField(blank=True)),
                ('postal', models.IntegerField(blank=True)),
                ('city', models.TextField(blank=True)),
                ('state', models.TextField(blank=True)),
                ('country', models.TextField(blank=True)),
                ('vis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.visitor')),
            ],
        ),
    ]
