# Generated by Django 3.2.4 on 2021-08-13 10:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210812_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emailAddress',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
