# Generated by Django 3.2.4 on 2021-08-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullsite', '0002_auto_20210814_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
