# Generated by Django 3.2.4 on 2021-08-24 15:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('fullsite', '0007_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phonenum', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('alternative_phno', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('pincode', models.IntegerField(max_length=999999)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('houseadd', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=100)),
            ],
        ),
    ]
