# Generated by Django 3.2.4 on 2021-08-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullsite', '0009_orderplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
