# Generated by Django 3.2.6 on 2021-09-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210813_1537'),
        ('fullsite', '0010_alter_address_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ManyToManyField(to='authentication.User'),
        ),
        migrations.DeleteModel(
            name='Orderplace',
        ),
    ]
